# Generated by Django 3.2.7 on 2023-03-03 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorreading',
            options={'managed': True},
        ),
    ]
