# Generated by Django 3.2.7 on 2023-03-03 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sensorreading_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorreading',
            options={'managed': False},
        ),
    ]
