# Generated by Django 3.2.7 on 2023-03-14 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230309_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileupload',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
