# Generated by Django 3.2.7 on 2023-03-22 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_operation_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorFileOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileupload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fileupload')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_operation', to='api.operation')),
            ],
        ),
    ]
