# Generated by Django 3.2.7 on 2022-12-21 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_purchase_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={},
        ),
    ]
