# Generated by Django 3.2.7 on 2023-03-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sensorfileoperation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='info_kvp',
            new_name='supp_kvp',
        ),
        migrations.RenameField(
            model_name='customerorder',
            old_name='invoice_file',
            new_name='supp_file',
        ),
        migrations.RenameField(
            model_name='customerorder',
            old_name='invoice_kvp',
            new_name='supp_kvp',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='manual_file',
            new_name='supp_file',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='info_kvp',
            new_name='supp_kvp',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='instruction_file',
            new_name='supp_file',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='info_kvp',
            new_name='supp_kvp',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='result_file',
            new_name='supp_file',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='result_kvp',
            new_name='supp_kvp',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='supplementary_file',
            new_name='supp_file',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='manual_file',
            new_name='supp_file',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='info_kvp',
            new_name='supp_kvp',
        ),
    ]
