# Generated by Django 3.2.7 on 2022-12-21 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_purchase_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['updated']},
        ),
    ]
